# 0. Connection credentials
spring.datasource.url=jdbc:mysql://localhost:3306/ledger?useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=ledger_user
spring.datasource.password=ledger_password

# 1. The JDBC Driver Class for MySQL
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# 2. Enable Flyway Migrations on Startup for this Profile
spring.flyway.enabled=true

# 3. Disable Hibernate's automatic schema generation
spring.jpa.hibernate.ddl-auto=none
# Why?
# Critical for PayPay/Banking alignment. 
# Hibernate has a feature to automatically generate tables based on your classes (update, create-drop).
# In a production system, never let Hibernate touch the schema.
# Flyway strictly owns the schema, so we set this to none (or validate to only verify without modifying)

# Log and format SQL queries in local console
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Logging
logging.structured.format.console=ecs
