# Redis server connection details
spring.data.redis.host=redis-14012.c11.us-east-1-3.ec2.cloud.redislabs.com
spring.data.redis.port=14012
spring.data.redis.password=${REDIS_PASSWORD:MBkZQLEC3BcvSshfsqVo54Yr49Zgt63k}
# Decouple from MySQL
spring.autoconfigure.exclude=org.springframework.boot.jdbc.autoconfigure.DataSourceAutoConfiguration,\
org.springframework.boot.hibernate.autoconfigure.HibernateJpaAutoConfiguration,\
org.springframework.boot.flyway.autoconfigure.FlywayAutoConfiguration

# Enable unwanted health-checks
management.health.redis.enabled=true
